### ISSUE TITLE
Can't create docs

### ISSUE THREAD

**Issue by sirrobert** [hugoduncan/codox-md#1]
Thanks for this -- I was just about to do something similar.  I have a new, tiny project (almost no code yet).  Codox works fine by itself.  When I install codox-md it's broken:
## Relevant details

Leiningen version:

```
$ lein --version
Leiningen 2.1.3 on Java 1.7.0_15 OpenJDK 64-Bit Server VM
```

Project.cli file

```
;; project.clj
(defproject myproject "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :dependencies [ [org.clojure/clojure "1.5.1"]
                  [clj-json "0.3.2"]
                  [org.clojure/java.jdbc "0.0.6"]
                  [ring-json-params "0.1.3"]
                  [compojure "1.1.5"]]
  :plugins [[lein-ring "0.8.3"]
            [lein-exec "0.2.1"]
            [codox "0.6.4"]
            [codox-md "0.2.0"]]
  :ring {:handler myproject.server/server}
  :codox {:output-dir "doc/codox"
          :writer codox-md.writer/write-docs}
  :main myproject.core)
```
## Errors

```
$ lein doc
Exception in thread "main" java.lang.Exception: Could not load codox writer codox-md.writer
  at codox.main$writer$fn__175.invoke(main.clj:13)
  at codox.main$writer.invoke(main.clj:9)
  at codox.main$generate_docs.invoke(main.clj:27)
  at user$eval183.invoke(NO_SOURCE_FILE:1)
  at clojure.lang.Compiler.eval(Compiler.java:6619)
  at clojure.lang.Compiler.eval(Compiler.java:6609)
  at clojure.lang.Compiler.eval(Compiler.java:6582)
  at clojure.core$eval.invoke(core.clj:2852)
  at clojure.main$eval_opt.invoke(main.clj:308)
  at clojure.main$initialize.invoke(main.clj:327)
  at clojure.main$null_opt.invoke(main.clj:362)
  at clojure.main$main.doInvoke(main.clj:440)
  at clojure.lang.RestFn.invoke(RestFn.java:421)
  at clojure.lang.Var.invoke(Var.java:419)
  at clojure.lang.AFn.applyToHelper(AFn.java:163)
  at clojure.lang.Var.applyTo(Var.java:532)
  at clojure.main.main(main.java:37)
Caused by: java.io.FileNotFoundException: Could not locate codox_md/writer__init.class or codox_md/writer.clj on classpath:
  at clojure.lang.RT.load(RT.java:443)
  at clojure.lang.RT.load(RT.java:411)
  at clojure.core$load$fn__5018.invoke(core.clj:5530)
  at clojure.core$load.doInvoke(core.clj:5529)
  at clojure.lang.RestFn.invoke(RestFn.java:408)
  at clojure.core$load_one.invoke(core.clj:5336)
  at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
  at clojure.core$load_lib.doInvoke(core.clj:5374)
  at clojure.lang.RestFn.applyTo(RestFn.java:142)
  at clojure.core$apply.invoke(core.clj:619)
  at clojure.core$load_libs.doInvoke(core.clj:5413)
  at clojure.lang.RestFn.applyTo(RestFn.java:137)
  at clojure.core$apply.invoke(core.clj:619)
  at clojure.core$require.doInvoke(core.clj:5496)
  at clojure.lang.RestFn.invoke(RestFn.java:408)
  at codox.main$writer$fn__175.invoke(main.clj:10)
  ... 16 more
Subprocess failed
```

**Comment by hugoduncan** [comment]
I think `codox-md` should be a dependency rather than a plugin.

**Comment by sirrobert** [comment]
Great, thanks.  I updated the README.md and sent a pull request.
